// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var alterPage, fetchRandom, searchStartups, umm, url;
    umm = 'd96b535e49275e48b04caa5c5df186b4c8d3f09b36672a65';
    url = 'https://api.angel.co/1';
    searchStartups = function() {
      var alphabets, rand, searchURL;
      alphabets = 'abcdefghijklmnopqurstuvwxyz';
      rand = alphabets.substr(Math.floor(Math.random() * 26), 1);
      searchURL = "" + url + "/search/?query=" + rand + "&type=Startup&access_token=" + umm;
      return $.ajax({
        url: searchURL,
        type: 'GET',
        dataType: 'JSONP',
        success: function(data) {
          return fetchRandom(data);
        }
      });
    };
    fetchRandom = function(data) {
      var startup, startupURL;
      startup = data[Math.floor(Math.random() * data.length)];
      startupURL = "" + url + "/startups/" + startup.id + "?access_token=" + umm;
      return $.ajax({
        url: startupURL,
        type: 'GET',
        dataType: 'JSONP',
        success: function(sdata) {
          return alterPage(sdata.name, sdata.company_url, sdata.product_desc);
        }
      });
    };
    alterPage = function(name, url, description) {
      $('#name').text(name);
      $('#url').text(url);
      return $('#desc').text(description);
    };
    return $('#explorer').on('click', function(e) {
      return searchStartups();
    });
  });

}).call(this);
