// Generated by CoffeeScript 1.4.0
(function() {

  $(function() {
    var alterPage, animateScore, fetchRandom, searchStartups, umm, url;
    umm = 'd96b535e49275e48b04caa5c5df186b4c8d3f09b36672a65';
    url = 'https://api.angel.co/1';
    searchStartups = function() {
      var alphabets, rand, searchURL;
      alphabets = 'abcdefghijklmnopqurstuvwxyz';
      rand = alphabets.substr(Math.floor(Math.random() * 26), 1);
      searchURL = "" + url + "/search/?query=" + rand + "&type=Startup&access_token=" + umm;
      return $.ajax({
        url: searchURL,
        type: 'GET',
        dataType: 'JSONP',
        success: function(data) {
          return fetchRandom(data);
        }
      });
    };
    fetchRandom = function(data) {
      var startup, startupURL;
      startup = data[Math.floor(Math.random() * data.length)];
      startupURL = "" + url + "/startups/" + startup.id + "?access_token=" + umm;
      return $.ajax({
        url: startupURL,
        type: 'GET',
        dataType: 'JSONP',
        success: function(sdata) {
          return alterPage(sdata.name, sdata.company_url, sdata.product_desc, sdata.quality);
        }
      });
    };
    alterPage = function(name, url, description, score) {
      $('#name').text(name);
      $('#url').text(url);
      $('#url').attr('href', url);
      $('#desc').text(description);
      return animateScore(score);
    };
    $('#explorer').on('click', function(e) {
      return searchStartups();
    });
    $(document).keydown(function(e) {
      if (e.which === 13) {
        return searchStartups();
      }
    });
    return animateScore = function(score) {
      return jQuery({
        Counter: 0
      }).animate({
        Counter: score
      }, {
        duration: 1000,
        easing: 'swing',
        step: function() {
          return $('#score').text(Math.ceil(this.Counter));
        }
      });
    };
  });

}).call(this);
